version: '3.9'

services:
  bsserver:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/BSserver
    environment:
      POSTGRES_URI: postgres://m:secret@postgres:5432/BrainScape
      REDIS_URI: redis://redis:6379
      NODE_OPTIONS: --legacy-watch
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/BSserver

  # Postgres 
  postgres:
    environment:
      POSTGRES_USER: m
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: BrainScape
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6380:6379"
      
