version: '3.9'

services:
  bsserver:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/BSserver
    environment:
      POSTGRES_URI: postgres://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
      REDIS_URI: redis://$REDIS_HOST:$REDIS_PORT
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/BSserver

  postgres:
    environment:
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    build: ./postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
